# MycoGraph-XL Workflow Configuration

# Project metadata
project_name: MycoGraph-XL
version: "0.1.0"
date: "2025-09-25"
pilot_mode: true

# Resource limits
max_threads: 16
max_memory: "64GB"
tmp_dir: "/tmp"

# Stage 0: Pre-filtering
min_fungal_signal: 0.01  # Minimum 1% fungal reads
min_read_length: 100     # Minimum read length
min_quality_score: 20    # Minimum base quality
max_human_contamination: 0.05  # Maximum 5% human reads for automatic inclusion
human_reprocess_threshold: 0.10  # Flag 5-10% for host-filtering

# Stage 1: Assembly & Gene Calling
assembler: "metaspades"  # Fallback to megahit if memory insufficient
min_contig_length: 1000
eukaryotic_selector: "eukrep"
gene_predictor:
  isolate: "funannotate"  # For near-complete assemblies
  metagenomic: "prodigal"  # For metagenomic bins
min_gene_completeness:
  isolate: 0.80  # For isolate-level assemblies
  metagenomic: 0.50  # For metagenomic bins

# Stage 2: Protein Clustering
mmseqs_sensitivity: 7.5
min_cluster_size: 3
similarity_threshold: 0.90

# Stage 3: Feature Extraction
protein_embedder: "esm2_t33_650M"  # ESM-2 medium model
domain_databases:
  - "Pfam"
  - "SMART"
  - "SignalP"
structure_db: "AlphaFoldDB"

# Stage 4: Advanced Modeling
deep_modeling:
  enabled: false  # Requires explicit approval
  max_structures: 100
  max_gpu_hours: 240

# Evaluation
holdout_fraction: 0.10
cv_folds: 5
metrics:
  - "precision@50"
  - "roc_auc"
  - "pr_auc"
  - "ece"