# FungiMap Demo Environment
# Minimal working configuration for M1 Mac demonstration

name: mycograph-xl-demo
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core Python
  - python=3.9
  - pip
  
  # Basic tools that are available
  - pandas
  - numpy
  - biopython
  - psutil
  - wget
  
  # Try to get these if available
  - snakemake-minimal
  - fastqc
  - multiqc
  
  # Pip dependencies (none for now)

# Resource limits for M1 Mac
variables:
  MALLOC_ARENA_MAX: 2
  OMP_NUM_THREADS: 4
  OPENBLAS_NUM_THREADS: 4